version: '3.9'

services:
    web:
        tty: true
        build: .
        ports:
            - "5555:5555"
        depends_on:
            - db_pg
        volumes:
            - .:/app
        environment:
            FLASK_ENV: development
    db_pg:
        image: "postgres:15.1"
        restart: always
        ports:
            - "5432:5432"
        environment:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: userpass
          POSTGRES_DB: testdb
